<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockScanTool.Contracts\StockScanTool.Contracts.csproj" />
    <ProjectReference Include="..\StockScanTool.Shared\StockScanTool.Shared.csproj" />
  </ItemGroup>

</Project>
