<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StockScanTool.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="7.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockScanTool.Contracts\StockScanTool.Contracts.csproj" />
  </ItemGroup>

</Project>
